# Generated by Django 5.0.6 on 2024-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('crdt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
